name: epub_viewer_bookmcface_example
description: Demonstrates how to use the epub_viewer_bookmcface plugin.

publish_to: "none"

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  epub_viewer_bookmcface:
    path: ../

  cupertino_icons: ^1.0.2

  permission_handler: 
  dio: 
  path_provider: 

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
